on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

name: Build - Push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: |
        dotnet build RestfulService.slnx --configuration Release
        dotnet tool restore
        dotnet tool run swagger tofile --output swagger.json RestfulService/bin/Release/net10.0/RestfulService.dll v1
      working-directory: src

    - name: Upload - swagger.json
      uses: actions/upload-artifact@v5
      with:
        name: swagger
        path: src/swagger.json
        if-no-files-found: error
