name: Deploy - Pages

on:
  workflow_run:
    workflows: ["Build - Push"]
    branches: [main]
    types:
    - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Download - Swagger artifact
      uses: actions/download-artifact@v8
      with:
        name: swagger
        run-id: ${{ github.event.workflow_run.id }}
        path: .github/pages/v1
        github-token: ${{ github.token }}

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: .github/pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
