name: Deploy - Pages

on:
  #workflow_run:
  #  workflows: ["Build - Push"]
  #  branches: [main]
  #  types:
  #  - completed
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    #if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - run: dotnet tool restore
      working-directory: src

    - run: dotnet build src/RestfulService.slnx --configuration Release

    - run: |
        mkdir -p ../.github/pages
        dotnet tool run swagger tofile --output ../.github/pages/swagger.json RestfulService/bin/Release/net10.0/RestfulService.dll v1
      working-directory: src

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .github/pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
